


export const GET_MUSIC_RECORD_REQUEST = "GET_MUSIC_RECORD_REQUEST";
export const GET_MUSIC_RECORD_SUCCESS = "GET_MUSIC_RECORD_SUCCESS";
export const GET_MUSIC_RECORD_FAILURE = "GET_MUSIC_RECORD_FAILURE";

export const DELETE_MUSIC_RECORD_REQUEST = "DELETE_MUSIC_RECORD_REQUEST";
export const DELETE_MUSIC_RECORD_SUCCESS = "DELETE_MUSIC_RECORD_SUCCESS";
export const DELETE_MUSIC_RECORD_FAILURE = "DELETE_MUSIC_RECORD_FAILURE";

export const ADD_MUSIC_RECORD_REQUEST = "ADD_MUSIC_RECORD_REQUEST";
export const ADD_MUSIC_RECORD_SUCCESS = "ADD_MUSIC_RECORD_SUCCESS";
export const ADD_MUSIC_RECORD_FAILURE = "ADD_MUSIC_RECORD_FAILURE";

export const EDIT_MUSIC_RECORD_REQUEST = "EDIT_MUSIC_RECORD_REQUEST";
export const EDIT_MUSIC_RECORD_SUCCESS = "EDIT_MUSIC_RECORD_SUCCESS";
export const EDIT_MUSIC_RECORD_FAILURE = "EDIT_MUSIC_RECORD_FAILURE";

export const UPDATE_MUSIC_RECORD_REQUEST = "UPDATE_MUSIC_RECORD_REQUEST";
export const UPDATE_MUSIC_RECORD_SUCCESS = "UPDATE_MUSIC_RECORD_SUCCESS";
export const UPDATE_MUSIC_RECORD_FAILURE = "UPDATE_MUSIC_RECORD_FAILURE";

export const SET_ALBUM_UPDATED = "SET_ALBUM_UPDATED";