export const POST_TODO_REQ="POST_TODO_REQ"
export const POST_TODO_FAIL="POST_TODO_FAIL"
export const POST_TODO_SUCCESS="POST_TODO_SUCCESS"
export const GET_TODO_FAILURE="GET_TODO_FAILURE"
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS"
export const GET_TODO_REQ="GET_TODO_REQ"

